### ISSUE TITLE
Should we close connection when flag is EOF in Wait method

### ISSUE THREAD

**Issue by dangngoctam00** [smallnest/epoller#11]
Hello, should we close connection at this line: https://github.com/smallnest/epoller/blob/82e19a072ec850da6db1ac6a946b24e794182b39/epoll_bsd.go#L152C5-L152C17
```golang
if (events[i].Flags & syscall.EV_EOF) == syscall.EV_EOF {
     conn.Close()
}
```
If we close connection then the read function does not have chance to read remaining byte in buffer. I think so.
Btw, thanks for your work, it helps me understanding about epoll 😊

**Comment by StarpTech** [comment]
Hi, we made similar observation. When running the tests in the library with`-race` 

```
 epoll_test.go:111: epoller does not work. expect 1100 bytes but got 1078 bytes
```

After removing the `conn.Close` the issue disappears.

OS: Mac

The docs around epoll strengthen this

```
If the read direction of	the socket  has	 shut-
down,  then  the	 filter	 also  sets  EV_EOF in
flags, and returns the socket error (if any) in
fflags.	It is possible for EOF to be  returned
(indicating the connection is gone) while there
is still	data pending in	the socket buffer.
```

Reference: https://man.freebsd.org/cgi/man.cgi?query=kqueue&sektion=2

**Comment by smallnest** [comment]
@StarpTech can you submit a PR?

**Comment by StarpTech** [comment]
@smallnest the same is true for linux
