### ISSUE TITLE
Deadlock in Wait() and WaitWithBuffer()

### ISSUE THREAD

**Issue by coanor** [smallnest/epoller#4]
The [code](https://github.com/smallnest/epoller/blob/5f1fffd432e3777a1d30e9cb0324d421dc13a724/epoll_bsd.go#L134) seems dead lock, the same in `WaitWithBuffer()`

**Comment by smallnest** [comment]
Need more details

**Comment by smallnest** [comment]
how did you find deadlock and what is the case?
