### ISSUE TITLE
The net.Conn it returns is no longer the original net.Conn object

### ISSUE THREAD

**Issue by cfsghost** [smallnest/epoller#9]
After updating to version 1.0.0, we've encountered a change in the behavior of `WaitWithBuffer()`. The `net.Conn` it returns is no longer the original `net.Conn` object. This can cause issues because we used to associate certain state information with the Connection object, but now we can't identify or access this state information using the returned `net.Conn`. As a result, it's becoming challenging to integrate with our actual application.

I suggest that we transform `connImpl` into a publicly accessible struct provided by epoller, for example, let's call it `ConnInfo`. Additionally, we should provide methods to retrieve the original `net.Conn` object to address this need in our application. This will help us maintain compatibility and ensure a smoother integration process.

**Comment by smallnest** [comment]
make ConnImpl exported so you can use type switch to get ConnImpl and get the underlying net.Conn
